pkgname <- "spict"
source(file.path(R.home("share"), "R", "examples-header.R"))
options(warn = 1)
library('spict')

base::assign(".oldSearch", base::search(), pos = 'CheckExEnv')
cleanEx()
nameEx("calc.osa.resid")
### * calc.osa.resid

flush(stderr()); flush(stdout())

### Name: calc.osa.resid
### Title: Calculate one-step-ahead residuals.
### Aliases: calc.osa.resid

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
rep <- calc.osa.resid(rep)
plotspict.osar(rep)



cleanEx()
nameEx("check.inp")
### * check.inp

flush(stderr()); flush(stdout())

### Name: check.inp
### Title: Check list of input variables
### Aliases: check.inp

### ** Examples

data(pol)
(inp <- check.inp(pol$albacore))



cleanEx()
nameEx("extract.simstats")
### * extract.simstats

flush(stderr()); flush(stdout())

### Name: extract.simstats
### Title: Extracts relevant statistics from the estimation of a simulated
###   data set.
### Aliases: extract.simstats

### ** Examples

data(pol)
repin <- fit.spict(pol$albacore)
sim <- sim.spict(repin)
rep <- fit.spict(sim)
extract.simstats(rep)



cleanEx()
nameEx("fit.meyermillar")
### * fit.meyermillar

flush(stderr()); flush(stdout())

### Name: fit.meyermillar
### Title: Fit the model of Meyer & Millar (1999)
### Aliases: fit.meyermillar

### ** Examples

priors <- list()
priors$K <- c(5.042905, 3.76)
priors$r <- c(-1.38, 3.845)
priors$iq <- c(0.001, 0.0012)
priors$itau2 <- c(1.709, 0.00861342)
priors$isigma2 <- c(3.785518, 0.0102232)
priors$logPini <- -0.223
data(pol)
inp <- pol$albacore
inp$meyermillar$n.iter <- 10000
inp$meyermillar$burnin <- 1000
inp$meyermillar$thin <- 10
inp$meyermillar$n.chains <- 1
inp$meyermillar$priors <- priors
res <- fit.meyermillar(inp)
summary(res$jags)



cleanEx()
nameEx("fit.spict")
### * fit.spict

flush(stderr()); flush(stdout())

### Name: fit.spict
### Title: Fit a continuous-time surplus production model to data.
### Aliases: fit.spict

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
Bmsy <- get.par('logBmsy', rep, exp=TRUE)
summary(rep)
plot(rep)



cleanEx()
nameEx("get.par")
### * get.par

flush(stderr()); flush(stdout())

### Name: get.par
### Title: Extract parameters from a result report as generated by
###   fit.spict.
### Aliases: get.par list.quantities

### ** Examples

## Make the south Atlantic albacore assessment
data(pol)
rep <- fit.spict(pol$albacore)

## See all quantitites that can be extracted
list.quantities(rep)

## Extract the Bmsy reference point
Bmsy <- get.par('logBmsy', rep, exp=TRUE)

## Extract the exploitable biomass estimates
Best <- get.par('logB', rep, exp=TRUE)

## Extract the estimated caryting capacity
K <- get.par('logK', rep, exp=TRUE)



cleanEx()
nameEx("likprof.spict")
### * likprof.spict

flush(stderr()); flush(stdout())

### Name: likprof.spict
### Title: Create profile likelihood
### Aliases: likprof.spict

### ** Examples

data(pol)
inp <- pol$albacore
inp$likprof <- list()
inp$likprof$pars <- 'logK'
inp$likprof$parrange <- c(log(80), log(400))
inp$likprof$nogridpoints <- 15
rep <- fit.spict(inp)
rep <- likprof.spict(rep)
plotspict.likprof(rep, logpar=TRUE)



cleanEx()
nameEx("manage")
### * manage

flush(stderr()); flush(stdout())

### Name: manage
### Title: Calculate predictions under different management scenarios
### Aliases: manage

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
repman <- manage(rep)
mansummary(repman) # To print projections



cleanEx()
nameEx("plot.spictcls")
### * plot.spictcls

flush(stderr()); flush(stdout())

### Name: plot.spictcls
### Title: Plot summarising spict results.
### Aliases: plot.spictcls

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plot(rep)



cleanEx()
nameEx("plotspict.bbmsy")
### * plotspict.bbmsy

flush(stderr()); flush(stdout())

### Name: plotspict.bbmsy
### Title: Plot estimated B/Bmsy.
### Aliases: plotspict.bbmsy

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plotspict.bbmsy(rep)



cleanEx()
nameEx("plotspict.biomass")
### * plotspict.biomass

flush(stderr()); flush(stdout())

### Name: plotspict.biomass
### Title: Plot estimated biomass.
### Aliases: plotspict.biomass

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plotspict.biomass(rep)



cleanEx()
nameEx("plotspict.catch")
### * plotspict.catch

flush(stderr()); flush(stdout())

### Name: plotspict.catch
### Title: Plot observed catch and predictions.
### Aliases: plotspict.catch

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plotspict.catch(rep)



cleanEx()
nameEx("plotspict.diagnostic")
### * plotspict.diagnostic

flush(stderr()); flush(stdout())

### Name: plotspict.diagnostic
### Title: Plot model diagnostic (data, residuals, and more)
### Aliases: plotspict.diagnostic

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
rep <- calc.osa.resid(rep)
plotspict.diagnostic(rep)



cleanEx()
nameEx("plotspict.f")
### * plotspict.f

flush(stderr()); flush(stdout())

### Name: plotspict.f
### Title: Plot estimated fishing mortality.
### Aliases: plotspict.f

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plotspict.f(rep)



cleanEx()
nameEx("plotspict.fb")
### * plotspict.fb

flush(stderr()); flush(stdout())

### Name: plotspict.fb
### Title: Plot fishing mortality versus biomass.
### Aliases: plotspict.fb

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plotspict.fb(rep)



cleanEx()
nameEx("plotspict.ffmsy")
### * plotspict.ffmsy

flush(stderr()); flush(stdout())

### Name: plotspict.ffmsy
### Title: Plot estimated relative fishing mortality.
### Aliases: plotspict.ffmsy

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plotspict.ffmsy(rep)



cleanEx()
nameEx("plotspict.osar")
### * plotspict.osar

flush(stderr()); flush(stdout())

### Name: plotspict.osar
### Title: Plot one-step-ahead residuals
### Aliases: plotspict.osar

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
rep <- calc.osa.resid(rep)
plotspict.osar(rep)



cleanEx()
nameEx("plotspict.production")
### * plotspict.production

flush(stderr()); flush(stdout())

### Name: plotspict.production
### Title: Plot theoretical production curve and estimates.
### Aliases: plotspict.production

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plotspict.production(rep)



cleanEx()
nameEx("plotspict.tc")
### * plotspict.tc

flush(stderr()); flush(stdout())

### Name: plotspict.tc
### Title: Plot time constant.
### Aliases: plotspict.tc

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
plotspict.tc(rep)



cleanEx()
nameEx("pol")
### * pol

flush(stderr()); flush(stdout())

### Name: pol
### Title: Fisheries data included in Polacheck et al. (1993).
### Aliases: pol
### Keywords: datasets

### ** Examples

data(pol)
rep <- fit.spict(inp=pol$albacore)
rep <- fit.spict(inp=pol$hake)
rep <- fit.spict(inp=pol$lobster)



cleanEx()
nameEx("read.aspic")
### * read.aspic

flush(stderr()); flush(stdout())

### Name: read.aspic
### Title: Reads ASPIC input file.
### Aliases: read.aspic

### ** Examples

## Not run: 
##D filename <- 'YFT-SSE.a7inp' # or some other ASPIC 7 input file
##D inp <- read.aspic(filename)
##D rep <- fit.spict(inp)
##D summary(rep)
##D plot(rep)
## End(Not run)



cleanEx()
nameEx("retro")
### * retro

flush(stderr()); flush(stdout())

### Name: retro
### Title: Conduct retrospective analysis
### Aliases: retro

### ** Examples

data(pol)
inp <- pol$albacore
rep <- fit.spict(inp)
rep <- retro(rep, nretroyear=6)
plotspict.retro(rep)



cleanEx()
nameEx("sim.spict")
### * sim.spict

flush(stderr()); flush(stdout())

### Name: sim.spict
### Title: Simulate data from Pella-Tomlinson model
### Aliases: sim.spict

### ** Examples

data(pol)
repin <- fit.spict(pol$albacore)
# Simulate a specific number of observations
inp <- list()
inp$dteuler <- 1/4 # To reduce calculation time
inp$ini <- repin$inp$ini
inp$ini$logF <- NULL
inp$ini$logB <- NULL
set.seed(1)
sim <- sim.spict(inp, nobs=150)
repsim <- fit.spict(sim)
summary(repsim) # Note true values are listed in the summary
plot(repsim) # Note true states are shown with orange colour

# Simulate data with seasonal F
inp <- list()
inp$dteuler <- 1/4
inp$nseasons <- 2
inp$splineorder <- 1
inp$obsC <- 1:80
inp$obsI <- 1:80
inp$ini <- repin$inp$ini
inp$ini$logF <- NULL
inp$ini$logB <- NULL
inp$ini$logphi <- log(2) # Seasonality introduced here
inp <- check.inp(inp)
sim2 <- sim.spict(inp)
par(mfrow=c(2, 1))
plot(sim2$obsC, typ='l')
plot(sim2$obsI[[1]], typ='l')



graphics::par(get("par.postscript", pos = 'CheckExEnv'))
cleanEx()
nameEx("spict")
### * spict

flush(stderr()); flush(stdout())

### Name: spict
### Title: Fits a continuous-time surplus production model to data
### Aliases: spict spict-package
### Keywords: assessment fisheries, model, production

### ** Examples

rep <- test.spict()



cleanEx()
nameEx("spict2DLMtool")
### * spict2DLMtool

flush(stderr()); flush(stdout())

### Name: spict2DLMtool
### Title: Get function to estimate TAC for the DLMtool package
### Aliases: spict2DLMtool

### ** Examples

## Not run: 
##D library(DLMtool)
##D 
##D ## Put together an operating model from the available DLM toolkit examples
##D StockEx <- Herring
##D FleetEx <- Generic_IncE
##D ObsEx <- Precise_Unbiased
##D 
##D ## Remove changes in life history parameters
##D StockEx@Mgrad <- c(0,0)
##D StockEx@Kgrad <- c(0,0)
##D StockEx@Linfgrad <- c(0,0)
##D StockEx@Prob_staying <- c(1,1)
##D 
##D ## Set the depletion level 
##D StockEx@D <- c(0.3, 0.4)
##D 
##D ## create Operation Model
##D OMex <- new("OM", Stock = StockEx, Fleet = FleetEx, 
##D                   Obs = ObsEx)
##D 
##D ## Set simulation options
##D OMex@nsim <- 10
##D OMex@nyears <- 25
##D OMex@proyears <- 3
##D 
##D ## Get SPiCT HCR
##D MPname <- spict2DLMtool(percentileC=0.3)
##D 
##D ## run MSE
##D MSEex <- runMSE(OMex, MPs = MPname,
##D             interval = 1, reps = 1, timelimit = 150, CheckMPs = FALSE)
## End(Not run)





cleanEx()
nameEx("summary.spictcls")
### * summary.spictcls

flush(stderr()); flush(stdout())

### Name: summary.spictcls
### Title: Output a summary of a fit.spict() run.
### Aliases: summary.spictcls

### ** Examples

data(pol)
rep <- fit.spict(pol$albacore)
summary(rep)



cleanEx()
nameEx("test.spict")
### * test.spict

flush(stderr()); flush(stdout())

### Name: test.spict
### Title: Example of a spict analysis.
### Aliases: test.spict

### ** Examples

rep <- test.spict()



cleanEx()
nameEx("validate.spict")
### * validate.spict

flush(stderr()); flush(stdout())

### Name: validate.spict
### Title: Simulate data and reestimate parameters
### Aliases: validate.spict

### ** Examples

data(pol)
rep0 <- fit.spict(pol$albacore)
inp <- list()
inp$ini <- rep0$pl
set.seed(1234)
validate.spict(inp, nsim=10, invec=c(30, 60), backup='validate.RData')



cleanEx()
nameEx("write.aspic")
### * write.aspic

flush(stderr()); flush(stdout())

### Name: write.aspic
### Title: Takes a SPiCT input list and writes it as an Aspic input file.
### Aliases: write.aspic

### ** Examples

data(pol)
sim <- (pol$albacore)
write.aspic(sim)



### * <FOOTER>
###
options(digits = 7L)
base::cat("Time elapsed: ", proc.time() - base::get("ptime", pos = 'CheckExEnv'),"\n")
grDevices::dev.off()
###
### Local variables: ***
### mode: outline-minor ***
### outline-regexp: "\\(> \\)?### [*]+" ***
### End: ***
quit('no')
